[package]
name = "shims"
version = "0.1.0"
authors = ["RACE Two Six Team <race@twosixlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
