
// 
// Copyright 2023 Two Six Technologies
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 

#ifndef __SOURCE_MESSAGE_SERIALIZER_H__
#define __SOURCE_MESSAGE_SERIALIZER_H__

#include <ClrMsg.h>

#include <string>
#include <vector>

class MessageSerializer {
public:
    /**
     * @brief Serialize a ClrMsg object into a string that can be sent over the RACE network.
     *
     * @param message A ClrMsg object to serialize.
     * @return std::string A serialized string of message.
     */
    static std::string serialize(const ClrMsg &message);

    /**
     * @brief Deserialize a ClrMsg that has been serialized by serialize().
     *
     * @param serializdMessage A serialized string of a ClrMsg generated by serialize().
     * @return ClrMsg The deserialized ClrMsg.
     */
    static ClrMsg deserialize(const std::string &serializdMessage);
};

#endif
